# Generated by Django 2.1.7 on 2019-04-06 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': '이미 존재하는 메일주소입니다.'}, max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'coordinator'), (3, 'parent')])),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoordinatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('university', models.CharField(max_length=100, verbose_name='university')),
                ('major', models.CharField(max_length=100, verbose_name='major')),
                ('classOf', models.IntegerField(verbose_name='class of')),
                ('CSATScore', models.IntegerField(verbose_name='CSAT score')),
                ('schoolScore', models.IntegerField(verbose_name='school score')),
                ('CSATScoreImage', models.ImageField(upload_to='', verbose_name='CAST score image')),
                ('schoolScoreImage', models.ImageField(upload_to='', verbose_name='school score image')),
                ('profileImage', models.ImageField(upload_to='', verbose_name='profile picture')),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('schoolYear', models.CharField(max_length=30, verbose_name='school year')),
                ('major', models.CharField(max_length=30, verbose_name='major')),
                ('addressState', models.CharField(max_length=100, verbose_name='address_state')),
                ('addressCity', models.CharField(max_length=100, verbose_name='address_city')),
                ('addressDetail', models.CharField(max_length=100, verbose_name='address_detail')),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
